name: configure-aws-credentials
description: configure-aws-credentials with role

inputs:
  role_to_assume:
    description: 'role-to-assume'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-northeast-1
        role-to-assume: ${{ inputs.role_to_assume }}
        role-session-name: GithubActionsSession