CREATE TABLE posts (
  post_id SERIAL PRIMARY KEY,
  auth_id VARCHAR(50) NOT NULL,
  username VARCHAR(20) NULL,
  post_text VARCHAR(140) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (auth_id) REFERENCES users(auth_id) ON DELETE CASCADE
);