name: initialize-pnpm
description: initialize pnpm

runs:
  using: 'composite'
  steps:
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'

    - name: Use Pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 8.10.2
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-